apiVersion: v1
kind: Pod
metadata: 
  name: my-ns-pod
  namespace: my-ns
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox 
    command: ['sh', '-c', 'echo hello k8s! && sleep 3600'] 

