apiVersion: v1
kind: Pod
metadata:
  name: my-config-pod-volume
spec:
  containers: 
  - name: myconfigpod
    image: busybox
    command: ['sh', '-c', "echo $(cat /etc/config/myKey) && sleep 3600"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap: 
        name: myconfigmap
