apiVersion: v1
kind: Pod
metadata:
  name: mycmdarg
  labels:
    app: mycmdarg
spec:
  containers:
  - name: myapparg-container
    image: busybox
    command: ['echo']
    args: ['This is my custom argument']
  restartPolicy: Never
