apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp-1
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello k8s ! &&sleep 3600']
