apiVersion: v1
kind: Pod
metadata:
  name: mycmdpodresourcelimit
  labels:
    app: mycmdpodresourcelimit
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh','-c',"echo New limit pod && sleep 3600"]
    resources: 
      requests: 
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
