apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers: 
  - name: myapp-container
    image: busybox
    command: ['sh','-c',"echo Hello, k8s!!! && sleep 3600"]
    env:
    - name: my_password
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: myKey
